export { Hero } from "./Hero";
export { Reasons } from "./Reasons";
export { ReasonCard } from "./ReasonCard";
export { Advantages } from "./Advantages";
export { AdvantageCard } from "./AdvantageCard";
export { Roadmap } from "./Roadmap";
export { CallToAction } from "./CallToAction";
export { Nav } from "./Nav";
export { Footer } from "./Footer";
