[package]
name = "coredin"
description = "A profesional talent network build on Coreum blockchain"
version = "0.1.0"
authors = ["Igor Peric <igorperic@live.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://gitlab.com/cryptonize/coredin"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
# cosmwasm-std = "2.1.3"
cosmwasm-std = "1.5.7" # coreum-test-tube requires this version
cw-storage-plus = "1.2.0"
thiserror = { version = "1.0.23" }
schemars = "0.8.1"
serde = { version = "1.0.125", default-features = false, features = ["derive"] }
cosmwasm-schema = "2.1.3"
coreum-wasm-sdk = "1.0.0"
cargo-post = "0.1.7"
sha2 = "0.10.8"
hex = "0.4.3"
sha3 = "0.10.8"
base64 = "0.13.0"
prost = "0.12.4"

[dev-dependencies]
cosmwasm-schema = { version = "2.0.0" }
coreum-test-tube = "4.0.0"
